name: Build WiX Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Specify the label of your self-hosted runner here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build WiX Installer
        run: |
          # Your WiX Toolset build commands here
          candle -nologo -out build wix.wxs
          light -nologo -out wix.msi build.wixobj

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: wix.msi
