name: Build MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Set path for candle and light
      run: |
        echo "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin" >> $GITHUB_PATH
      shell: bash

    - name: Compile WiX Project
      run: candle wix.wxs -o output  # Compile WiX source and specify output directory

    - name: Link WiX Object Files
      run: light output\*.wixobj -o myapp.msi  # Link WiX object files and generate MSI file
