name: Build MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build MSI
        run: |
          # Specify the full path to candle.exe with quotes
          $candlePath = "C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe"
          $wixSourceFile = "wix.wxs"
          $outputWixobjFile = "wix.wixobj"

          # Run candle.exe
          & $candlePath $wixSourceFile -o $outputWixobjFile

          # Specify the full path to light.exe with quotes
          $lightPath = "C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe"
          $outputMsiFile = "wix.msi"

          # Run light.exe
          & $lightPath $outputWixobjFile -o $outputMsiFile
