name: Build MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install WiX Toolset
        run: |
          # Download WiX Toolset
          Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip' -OutFile 'wix311-binaries.zip'

          # Extract WiX Toolset
          Expand-Archive -Path 'wix311-binaries.zip' -DestinationPath $env:ProgramFiles\WiX

      - name: Set up WiX environment
        run: |
          # Add WiX Toolset to PATH
          $env:Path += ";$($env:ProgramFiles)\WiX\bin"

      - name: Build MSI 
        shell: pwsh
        run:
          cd . .
          candle.exe wix.wxs
          light.exe wix.wixobj

