name: Build MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build MSI
        run: |
          # Specify the full path to candle.exe and light.exe with URL-encoded spaces
          $candlePath = "file:///C:/Program%20Files%20(x86)/WiX%20Toolset%20v3.14/bin/candle.exe"
          $lightPath = "file:///C:/Program%20Files%20(x86)/WiX%20Toolset%20v3.14/bin/light.exe"
          $wixSourceFile = "wix.wxs"
          $outputWixobjFile = "wix.wixobj"
          $outputMsiFile = "wix.msi"

          # Run candle.exe to compile the WiX source file
          & $candlePath $wixSourceFile -o $outputWixobjFile

          # Run light.exe to link the object files into an MSI
          & $lightPath $outputWixobjFile -o $outputMsiFile

          # Display the paths for verification
          Write-Host "candlePath: $candlePath"
          Write-Host "lightPath: $lightPath"
          Write-Host "wixSourceFile: $wixSourceFile"
          Write-Host "outputWixobjFile: $outputWixobjFile"
          Write-Host "outputMsiFile: $outputMsiFile"
