name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone osquery repository
      run: git clone https://github.com/osquery/osquery.git
      working-directory: ${{ github.workspace }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: ${{ github.workspace }}/osquery/tools
