name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-leatst 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone osquery repository
      run: git clone https://github.com/osquery/osquery.git
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: ./osquery

